apiVersion: cert-manager.io/v1
kind: {{ .Values.ca.type }}
metadata:
  name: {{ .Values.ca.name }}
  namespace: default
spec:
  {{ if eq (lower .Values.ca.from) "vault" }}
  vault:
    path: pki/sign/{{ .Release.Name }}
    server: http://{{ default "vault-internal.core" .Values.vault_addr }}:8200
    auth:
      kubernetes:
        role: {{ include "RideSaver.serviceAccountName" . }}
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: {{ include "RideSaver.serviceAccountName" . }}
          key: token
  {{ end }}
