{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "RideSaver.serviceAccountName" . }}-admin
  labels:
    {{- include "RideSaver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "RideSaver.serviceAccountName" . }}-admin
  annotations:
    kubernetes.io/service-account.name: {{ include "RideSaver.serviceAccountName" . }}-admin
type: kubernetes.io/service-account-token
data:
{{- end }}
