repositories:
  # - name: UI
  #   url: https://RideSaver.github.io/UI
  - name: LyftClient
    url: https://RideSaver.github.io/LyftAPI_Client
  - name: LyftMock
    url: https://RideSaver.github.io/MockAPI_Lyft
  - name: UberClient
    url: https://RideSaver.github.io/UberAPI_Client
  - name: UberMock
    url: https://RideSaver.github.io/MockAPI_Uber

  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: nginx
    url: https://helm.nginx.com/stable
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  # - name: UI
  #   namespace: server
  #   chart: UI/RideSaver_UI
  - name: lyft-mock
    namespace: mock
    chart: LyftMock/RideSaver_Mock_Lyft
    values:
      - fullnameOverride: lyft
      - settings.yaml
  - name: lyft-client
    namespace: client
    chart: LyftClient/LyftClient
    values:
      - fullnameOverride: lyft
      - settings.yaml
  - name: uber-mock
    namespace: mock
    chart: UberMock/RideSaver_Mock_Uber
    values:
      - fullnameOverride: uber
      - settings.yaml
  - name: uber-client
    namespace: client
    chart: UberClient/RideSaver_Client_Uber
    values:
      - fullnameOverride: uber
      - settings.yaml
helmfiles:
  - path: git::https://github.com/RideSaver/RideSaver_API_Server.git@charts/helmfile.yaml?ref=main
    values:
      - settings.yaml
      - namespace: api

environments:
  default:
    values:
      - settings.yaml
