environments:
  default:
    values:
      - ingress:
          enabled: true
          hosts:
            - host: ride-saver.online
              paths:
                - path: /
                  pathType: ImplementationSpecific
        redis:
          replicas: 1
        vault_addr: vault.core
        imagePullSecrets:
          - ghcr-token